#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Aug 13, 2024 12:05:03 PM BST  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #FFFFFF 
    wm focusmodel $top passive
    wm geometry $top 615x395+2557+71
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3825 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    button "$top.but47" \
        -activeforeground black -background #FF0000 \
        -font "-family {DejaVu Sans} -size 36 -weight bold" \
        -foreground #FFFFFF -highlightcolor #FFFFFF -text "STOP" 
    vTcl:DefineAlias "$top.but47" "Button1" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab53" \
        -activebackground #FFFFFF -activeforeground black -anchor w \
        -background #FFFFFF -compound left \
        -font "-family {DejaVu Sans} -size 13 -weight bold -slant italic" \
        -foreground #000000 -text "FreeBot Controls" 
    vTcl:DefineAlias "$top.lab53" "Label1" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but48" \
        -activebackground #d9d9d9 -activeforeground black -background #00FF00 \
        -font "-family {DejaVu Sans} -size 30 -weight bold" \
        -foreground #FFFFFF -text "START" 
    vTcl:DefineAlias "$top.but48" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but49" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -font "-family {DejaVu Sans} -size 10" -foreground #000000 \
        -text "VOLTAGE SEND ON" 
    vTcl:DefineAlias "$top.but49" "Button3" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but50" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -font "-family {DejaVu Sans} -size 10" -foreground #000000 \
        -text "VOLTAGE SEND OFF" 
    vTcl:DefineAlias "$top.but50" "Button4" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but51" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -font "-family {DejaVu Sans} -size 10" -foreground #000000 \
        -text "PLOT" 
    vTcl:DefineAlias "$top.but51" "Button5" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but47 \
        -in $top -x 0 -relx 0.033 -y 0 -rely 0.177 -width 171 -relwidth 0 \
        -height 111 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 0 -relx 0.358 -y 0 -rely 0.051 -width 0 -relwidth 0.291 \
        -height 0 -relheight 0.078 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 0 -relx 0.033 -y 0 -rely 0.557 -width 171 -relwidth 0 \
        -height 111 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.358 -y 0 -rely 0.177 -width 171 -relwidth 0 \
        -height 111 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 0 -relx 0.358 -y 0 -rely 0.557 -width 171 -relwidth 0 \
        -height 111 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 0 -relx 0.683 -y 0 -rely 0.177 -width 171 -relwidth 0 \
        -height 261 -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

