#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Aug 14, 2024 02:06:52 PM BST  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

import matplotlib.pyplot as plt
import serial

_location = os.path.dirname(__file__)

import fb_new_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40'

serial_port = '/dev/ttyACM2'  # Replace with your port
baud_rate = 115200



class Toplevel1:

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("709x545+2825+178")
        top.minsize(1, 1)
        top.maxsize(3825, 1050)
        top.resizable(1,  1)
        top.title("Toplevel 0")

        self.top = top

        self.recipient = None

        self.dkb = fb_new_support.DKB()

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.508, rely=0.055, relheight=0.266, relwidth=0.458)
        self.Frame1.configure(relief='groove',borderwidth="2")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.092, rely=0.069, height=31, width=279)
        self.Label1.configure(activebackground="#d9d9d9", anchor='w',compound='left', text='''Select the recepient of the command:''')

        self.boardcast = tk.Button(self.Frame1)
        self.boardcast.place(relx=0.062, rely=0.414, height=71, width=81)
        self.boardcast.configure(activebackground="#d9d9d9",text='''Broadcast''',command=lambda: self.set_recipient('broadcast'))

        self.FB1 = tk.Button(self.Frame1)
        self.FB1.place(relx=0.369, rely=0.414, height=71, width=81)
        self.FB1.configure(activebackground="#d9d9d9",font="-family {DejaVu Sans} -size 10",text='''FreeBot 1''',command=lambda: self.set_recipient('FB1'))

        self.FB2 = tk.Button(self.Frame1)
        self.FB2.place(relx=0.677, rely=0.414, height=71, width=81)
        self.FB2.configure(activebackground="#d9d9d9",font="-family {DejaVu Sans} -size 10",text='''FreeBot 2''',command=lambda: self.set_recipient('FB2'))

        self.Plot = tk.Button(self.top)
        self.Plot.place(relx=0.282, rely=0.055, height=161, width=141)
        self.Plot.configure(activebackground="#d9d9d9",font="-family {DejaVu Sans} -size 10", text='''PLOT / STOP LOG''')

        self.Log = tk.Button(self.top)
        self.Log.place(relx=0.056, rely=0.055, height=161, width=141)
        self.Log.configure(activebackground="#d9d9d9",text='''START LOGGING''')

        self.Start = tk.Button(self.top)
        self.Start.place(relx=0.127, rely=0.404, height=131, width=231)
        self.Start.configure(activebackground="#d9d9d9",text='''Move ON''')

        self.Stop = tk.Button(self.top)
        self.Stop.place(relx=0.127, rely=0.697, height=131, width=231)
        self.Stop.configure(activebackground="#d9d9d9",text='''Move OFF''')

        self.v_stop = tk.Button(self.top)
        self.v_stop.place(relx=0.55, rely=0.697, height=131, width=231)
        self.v_stop.configure(activebackground="#d9d9d9",font="-family {DejaVu Sans} -size 10",text='''Voltage Send OFF''')

        self.v_start = tk.Button(self.top)
        self.v_start.place(relx=0.55, rely=0.404, height=131, width=231)
        self.v_start.configure(activebackground="#d9d9d9",font="-family {DejaVu Sans} -size 10",text='''Voltage Send ON''')

    def set_recipient(self,recipient):
        self.recipient = recipient
    
    def voltage_send_on(self):
        if self.recipient == 'broadcast':
            self.dkb.ser.write(b'99d')
        elif self.recipient == 'FB1':
            self.dkb.ser.write(b'00d')
        elif self. recipient == 'FB2':
            self.dkb.ser.write(b'01d')
        else:
            print("No recipient selected")
    
    def voltage_send_off(self):
        if self.recipient == 'broadcast':
            self.dkb.ser.write(b'99c')
        elif self.recipient == 'FB1':
            self.dkb.ser.write(b'00c')
        elif self. recipient == 'FB2':
            self.dkb.ser.write(b'01c')
        else:
            print("No recipient selected")
  
        

if __name__ == '__main__':
    fb_new_support.main()





