#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Aug 13, 2024 12:02:04 PM BST  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import fb_control_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("615x395+2557+71")
        top.minsize(1, 1)
        top.maxsize(3825, 1050)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#FFFFFF")

        self.top = top

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.033, rely=0.177, height=111, width=171)
        self.Button1.configure(activebackground="#FF0000")
        self.Button1.configure(background="#FF0000")
        self.Button1.configure(font="-family {DejaVu Sans} -size 36 -weight bold")
        self.Button1.configure(foreground="#FFFFFF")
        self.Button1.configure(highlightcolor="#FFFFFF")
        self.Button1.configure(text='''STOP''')

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.358, rely=0.051, height=31, width=179)
        self.Label1.configure(activebackground="#FFFFFF")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#FFFFFF")
        self.Label1.configure(compound='left')
        self.Label1.configure(font="-family {DejaVu Sans} -size 13 -weight bold -slant italic")
        self.Label1.configure(text='''FreeBot Controls''')

        self.Button2 = tk.Button(self.top)
        self.Button2.place(relx=0.033, rely=0.557, height=111, width=171)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(background="#00FF00")
        self.Button2.configure(font="-family {DejaVu Sans} -size 30 -weight bold")
        self.Button2.configure(foreground="#FFFFFF")
        self.Button2.configure(text='''START''')

        self.Button3 = tk.Button(self.top)
        self.Button3.place(relx=0.358, rely=0.177, height=111, width=171)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(text='''VOLTAGE SEND ON''')

        self.Button4 = tk.Button(self.top)
        self.Button4.place(relx=0.358, rely=0.557, height=111, width=171)
        self.Button4.configure(activebackground="#d9d9d9")
        self.Button4.configure(text='''VOLTAGE SEND OFF''')

        self.Button5 = tk.Button(self.top)
        self.Button5.place(relx=0.683, rely=0.177, height=261, width=171)
        self.Button5.configure(activebackground="#d9d9d9")
        self.Button5.configure(text='''PLOT''')



if __name__ == '__main__':
    fb_control_support.main()




